run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocritic
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam

linters-settings:
  staticcheck:
    checks:
      - all

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam

