import { useState, useCallback } from 'react';
import toast from 'react-hot-toast';
import { useRelations } from '../../relations/hooks/useRelations';
import { useCapabilities, useRealizationsForComponents } from '../../capabilities/hooks/useCapabilities';
import { useComponents } from '../../components/hooks/useComponents';
import { useOriginRelationshipsQuery } from '../../origin-entities/hooks/useOriginRelationships';
import { useCreateView, useAddComponentToView, useAddCapabilityToView, useAddOriginEntityToView } from '../../views/hooks/useViews';
import { useAppStore } from '../../../store/appStore';
import { collectRelatedEntities, type EntityRef, type CollectedEntities } from '../utils/collectRelatedEntities';
import type { ComponentId, CapabilityId, ViewId } from '../../../api/types';

const MAX_VIEW_NAME_LENGTH = 100;

function buildViewName(entityName: string): string {
  const prefix = 'Autogenerated view for ';
  const maxEntityLength = MAX_VIEW_NAME_LENGTH - prefix.length;
  const truncatedName = entityName.length > maxEntityLength
    ? entityName.slice(0, maxEntityLength - 1) + '\u2026'
    : entityName;
  return `${prefix}${truncatedName}`;
}

function totalEntityCount(collected: CollectedEntities): number {
  return collected.componentIds.size + collected.capabilityIds.size + collected.originEntityIds.size;
}

interface AddMutations {
  addComponent: { mutateAsync: (args: { viewId: ViewId; request: { componentId: ComponentId; x: number; y: number } }) => Promise<void> };
  addCapability: { mutateAsync: (args: { viewId: ViewId; request: { capabilityId: CapabilityId; x: number; y: number } }) => Promise<void> };
  addOriginEntity: { mutateAsync: (args: { viewId: ViewId; request: { originEntityId: string; x: number; y: number } }) => Promise<void> };
}

function addEntitiesToView(viewId: ViewId, collected: CollectedEntities, mutations: AddMutations): Promise<void[]> {
  const ops: Promise<void>[] = [];
  for (const id of collected.componentIds) {
    ops.push(mutations.addComponent.mutateAsync({ viewId, request: { componentId: id as ComponentId, x: 0, y: 0 } }));
  }
  for (const id of collected.capabilityIds) {
    ops.push(mutations.addCapability.mutateAsync({ viewId, request: { capabilityId: id as CapabilityId, x: 0, y: 0 } }));
  }
  for (const id of collected.originEntityIds) {
    ops.push(mutations.addOriginEntity.mutateAsync({ viewId, request: { originEntityId: id, x: 0, y: 0 } }));
  }
  return Promise.all(ops);
}

export function useGenerateView() {
  const { data: relations = [] } = useRelations();
  const { data: capabilities = [] } = useCapabilities();
  const { data: components = [] } = useComponents();
  const componentIds = components.map((c) => c.id);
  const { data: realizations = [] } = useRealizationsForComponents(componentIds);
  const { data: originRelationships = [] } = useOriginRelationshipsQuery();

  const createViewMutation = useCreateView();
  const addComponent = useAddComponentToView();
  const addCapability = useAddCapabilityToView();
  const addOriginEntity = useAddOriginEntityToView();
  const setCurrentViewId = useAppStore((state) => state.setCurrentViewId);

  const [isGenerating, setIsGenerating] = useState(false);

  const generateView = useCallback(async (startEntity: EntityRef, entityName: string) => {
    setIsGenerating(true);
    try {
      const collected = collectRelatedEntities(startEntity, { relations, capabilities, realizations, originRelationships });
      const newView = await createViewMutation.mutateAsync({ name: buildViewName(entityName) });

      await addEntitiesToView(newView.id, collected, { addComponent, addCapability, addOriginEntity });
      setCurrentViewId(newView.id);

      const count = totalEntityCount(collected);
      const suffix = collected.truncated ? ' (graph was truncated at 500 limit)' : '';
      toast.success(`View generated with ${count} entities${suffix}`);
    } catch {
      toast.error('Failed to generate view');
    } finally {
      setIsGenerating(false);
    }
  }, [relations, capabilities, realizations, originRelationships, createViewMutation, addComponent, addCapability, addOriginEntity, setCurrentViewId]);

  return { generateView, isGenerating };
}
