apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: easi-db-credentials-es
  namespace: enterprisearchitecture-pnpbj
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secrets-manager-ss
  target:
    name: easi-db-credentials
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        admin-conn-string: "host=$(DB_HOST) port=$(DB_PORT) user={{ .rds_username }} password={{ .rds_password }} dbname=easi"
        easi-app-password: "{{ .app_password }}"
        easi-admin-password: "{{ .rds_password }}"
        DB_CONN_STRING: "host=$(DB_HOST) port=$(DB_PORT) user={{ .app_username }} password={{ .app_password }} dbname=easi"
  data:
  - secretKey: rds_username
    remoteRef:
      key: "rds!db-30146832-1030-47da-839f-d3ffaf6b2e33"
      property: username
  - secretKey: rds_password
    remoteRef:
      key: "rds!db-30146832-1030-47da-839f-d3ffaf6b2e33"
      property: password
  - secretKey: app_username
    remoteRef:
      key: easi/db-credentials
      property: app-username
  - secretKey: app_password
    remoteRef:
      key: easi/db-credentials
      property: app-password
