apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: easi-agent-token-secret-es
  namespace: enterprisearchitecture-pnpbj
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secrets-manager-ss
  target:
    name: easi-agent-token-secret
    creationPolicy: Owner
  data:
  - secretKey: agent-token-secret
    remoteRef:
      key: easi/agent-token-secret
      property: agent-token-secret
