apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: easi-platform-credentials-es
  namespace: enterprisearchitecture-pnpbj
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secrets-manager-ss
  target:
    name: easi-platform-credentials
    creationPolicy: Owner
  data:
  - secretKey: admin-api-key
    remoteRef:
      key: easi/platform-credentials
      property: admin-api-key
