apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: easi-oidc-credentials-es
  namespace: enterprisearchitecture-pnpbj
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: secrets-manager-ss
  target:
    name: easi-oidc-credentials
    creationPolicy: Owner
  data:
  - secretKey: client-secret
    remoteRef:
      key: easi/oidc-credentials
      property: client-secret
