apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secrets-manager-ss
  namespace: enterprisearchitecture-pnpbj
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-1
      auth:
        jwt:
          serviceAccountRef:
            name: secrets-manager-sa
