export interface ComponentDef {
  name: string;
  description: string;
}

const RAW: [string, string][] = [
  // Original 20 — names preserved for cross-references in relations, realizations, and views
  ["User Service", "Handles user authentication, authorization, and profile management"],
  ["Order Service", "Manages customer orders, order lifecycle, and order history"],
  ["Payment Gateway", "Processes payments, refunds, and integrates with payment providers"],
  ["Inventory Service", "Tracks product inventory levels and availability across warehouses"],
  ["Notification Service", "Sends emails, SMS, and push notifications to customers"],
  ["Product Catalog", "Manages product information, categories, and search functionality"],
  ["Shopping Cart", "Maintains shopping cart state and checkout process"],
  ["Analytics Platform", "Collects and processes business analytics and metrics"],
  ["Customer Portal", "Self-service portal for customer account management"],
  ["Admin Dashboard", "Internal tool for operations and support teams"],
  ["API Gateway", "Central entry point for all API requests with rate limiting and routing"],
  ["Message Queue", "Asynchronous message processing for event-driven architecture"],
  ["Cache Layer", "Redis-based caching for improved performance"],
  ["Search Engine", "Elasticsearch-powered full-text search capabilities"],
  ["Recommendation Engine", "ML-based product recommendations for customers"],
  ["Shipping Service", "Calculates shipping rates and tracks deliveries"],
  ["Pricing Service", "Dynamic pricing, discounts, and promotional rules engine"],
  ["Fraud Detection", "Real-time fraud detection for payment transactions"],
  ["Content Management", "Manages website content, banners, and marketing materials"],
  ["Reporting Service", "Generates business reports and data exports"],

  // Customer & Identity (28)
  ["CRM Core Platform", "Centralized customer relationship management and data hub"],
  ["Lead Management System", "Track, qualify, and route sales leads through the pipeline"],
  ["Account Management Platform", "Manage strategic customer accounts and relationships"],
  ["Contact Center Hub", "Omnichannel customer support operations and routing"],
  ["Customer Data Platform", "Unified customer data aggregation across all touchpoints"],
  ["Identity Service", "Digital identity lifecycle management and directory"],
  ["Loyalty Platform", "Customer loyalty programs, points tracking, and redemption"],
  ["Support Ticket System", "Issue tracking, routing, and resolution workflows"],
  ["Chat Service", "Real-time chat interface for customer support interactions"],
  ["Email Communication Service", "Transactional and marketing email delivery"],
  ["SMS Gateway", "SMS messaging for transactional notifications and alerts"],
  ["Push Notification Hub", "Mobile and web push notification delivery at scale"],
  ["Customer Survey Tool", "NPS and satisfaction survey creation and analysis"],
  ["Feedback Management System", "Collect, categorize, and analyze customer feedback"],
  ["Voice of Customer Platform", "Aggregate customer signals across all channels"],
  ["Customer Health Scoring Engine", "Real-time customer health and risk score calculation"],
  ["Churn Prediction Engine", "Identify at-risk customers before they churn"],
  ["Customer Journey Orchestrator", "Cross-channel customer journey automation"],
  ["Self-Service Portal", "Customer self-service account and order management"],
  ["Knowledge Base System", "Help articles and self-service content management"],
  ["Community Platform", "Customer community, forums, and peer support"],
  ["Customer Onboarding Hub", "Guided onboarding flows and activation for new customers"],
  ["Profile Management Service", "Customer profile data creation and synchronization"],
  ["Preference Center", "Customer communication and subscription preference management"],
  ["Consent Management Platform", "GDPR and privacy consent collection and auditing"],
  ["Customer Intelligence Hub", "Aggregated customer insights and behavioral profiles"],
  ["Relationship Analytics Platform", "Relationship health scoring and engagement metrics"],
  ["Next Best Action Engine", "AI-driven next best action recommendations per customer"],

  // Commerce (28)
  ["Product Configurator Service", "Complex product configuration and constraint engine"],
  ["Headless Commerce API", "Commerce APIs for decoupled and composable frontends"],
  ["Storefront Service", "Digital storefront rendering, routing, and management"],
  ["Category Management System", "Product taxonomy and category hierarchy management"],
  ["Catalog Syndication Hub", "Distribute product catalog data across sales channels"],
  ["Product Information Manager", "Central repository for product data and enrichment"],
  ["Digital Asset Manager", "Product images, videos, and media asset management"],
  ["AB Testing Platform", "Experiment on commerce UI, copy, and conversion flows"],
  ["Personalization Engine", "Real-time product and content personalization by segment"],
  ["Commerce Analytics Platform", "Commerce KPI tracking, funnels, and insights"],
  ["Cross-sell Engine", "Automated cross-sell recommendation generation"],
  ["Upsell Optimizer", "Identify and present upsell opportunities in real time"],
  ["Faceted Search Service", "Attribute-based product search and faceted filtering"],
  ["Inventory Reservation Service", "Temporarily reserve inventory during the checkout flow"],
  ["Order Orchestrator", "Multi-vendor order routing, splitting, and aggregation"],
  ["Cart Abandonment Recovery", "Detect and recover abandoned shopping carts via campaigns"],
  ["Wishlist Service", "Save, manage, and share customer product wishlists"],
  ["Product Review Platform", "Customer product ratings, reviews, and moderation"],
  ["Bundle Manager", "Create, price, and manage product bundles and kits"],
  ["Digital Commerce Platform", "All-in-one unified commerce management system"],
  ["Promotion Analytics", "Measure promotion performance, uplift, and ROI"],
  ["Marketplace Operations Hub", "Seller onboarding, listing, and marketplace governance"],
  ["Seller Portal", "Self-service portal for marketplace sellers to manage listings"],
  ["Order Tracking Service", "Real-time order status, fulfillment progress, and delivery ETA"],
  ["Returns Processing Hub", "Automated returns authorization and reverse logistics"],
  ["Checkout Analytics", "Funnel analysis and checkout friction identification"],
  ["Product Lifecycle Manager", "Manage product stages from launch to discontinuation"],
  ["Price Intelligence Engine", "Competitive price monitoring and automated repricing"],

  // Payments & Finance (28)
  ["Invoice Manager", "Automated invoice generation, delivery, and status tracking"],
  ["Billing Platform", "Recurring, usage-based, and one-time billing management"],
  ["Revenue Recognition Engine", "Automate ASC 606 / IFRS 15 revenue recognition rules"],
  ["Accounts Payable Hub", "Supplier invoice processing, approval, and payment"],
  ["Accounts Receivable Manager", "Customer collections, cash application, and aging"],
  ["Financial Reporting Platform", "Financial statements, management reports, and consolidation"],
  ["General Ledger Service", "Core double-entry accounting and journal entry management"],
  ["Treasury Management System", "Cash flow forecasting and liquidity management"],
  ["Tax Compliance Engine", "Tax calculation, filing automation, and audit support"],
  ["Currency Exchange Service", "Multi-currency conversion, hedging, and FX management"],
  ["Subscription Billing Platform", "Recurring subscription charge lifecycle management"],
  ["Chargeback Handler", "Payment dispute management and chargeback resolution workflows"],
  ["Payment Analytics Service", "Payment performance, conversion, and decline analytics"],
  ["Financial Forecasting Tool", "Rolling financial forecasts and scenario modeling"],
  ["Budget Management Platform", "Budget creation, approval workflow, and variance tracking"],
  ["Cost Allocation Service", "Allocate shared costs across business units and projects"],
  ["Profitability Analyzer", "Product, customer, and channel profitability analysis"],
  ["Fixed Assets Manager", "Asset depreciation schedules and lifecycle management"],
  ["Expense Tracking Platform", "Employee expense submission, approval, and reimbursement"],
  ["Financial Close Manager", "Month-end and year-end close process automation"],
  ["Compliance Reporting Engine", "Regulatory financial reporting automation and submission"],
  ["Payment Orchestrator", "Intelligent payment routing and provider optimization"],
  ["Escrow Service", "Secure fund holding for marketplace and high-value transactions"],
  ["Settlement Service", "Marketplace seller and partner payment settlement processing"],
  ["Risk Scoring Service", "Real-time transaction risk scoring and decisioning"],
  ["Fraud Analytics", "Fraud pattern detection, investigation, and case management"],
  ["AML Compliance Tool", "Anti-money laundering transaction monitoring and SAR filing"],
  ["Bank Reconciliation Service", "Automated bank statement matching and reconciliation"],

  // Supply Chain & Logistics (28)
  ["Warehouse Management System", "Inbound receiving, storage slotting, and outbound fulfillment"],
  ["Transportation Manager", "Freight planning, tender, and carrier execution"],
  ["Demand Planning Engine", "Statistical demand forecasting and consensus planning"],
  ["Supply Planning Service", "Supply balancing, allocation, and replenishment planning"],
  ["Procurement Platform", "Strategic sourcing, e-procurement, and spend management"],
  ["Supplier Portal", "Supplier self-service collaboration, PO acknowledgment, and invoicing"],
  ["Purchase Order Manager", "PO creation, approval workflow, and lifecycle tracking"],
  ["Receiving System", "Goods receipt recording, inspection, and putaway direction"],
  ["Picking and Packing Service", "Warehouse pick, pack, and labeling task management"],
  ["Freight Broker Integration", "Connect with freight broker networks and spot markets"],
  ["Customs Clearance Service", "Import and export customs documentation management"],
  ["Route Optimizer", "Multi-stop delivery route planning and optimization"],
  ["Last Mile Delivery Platform", "Customer delivery scheduling and driver dispatch"],
  ["Fleet Management System", "Vehicle tracking, fuel monitoring, and maintenance scheduling"],
  ["Cold Chain Monitor", "Temperature-sensitive shipment condition monitoring"],
  ["Quality Control Platform", "Product inspection workflows, sampling, and defect tracking"],
  ["Recall Management System", "Product recall coordination, notification, and tracking"],
  ["Vendor Scorecard Service", "Supplier KPI tracking, rating, and performance reviews"],
  ["Contract Manufacturing Manager", "Third-party manufacturing order and capacity coordination"],
  ["Bill of Materials Service", "Product structure, component linkage, and BOM versioning"],
  ["MRP Engine", "Materials requirements planning, lead time, and capacity scheduling"],
  ["Replenishment Optimizer", "Automated reorder point calculation and stock replenishment"],
  ["Carrier Selection Engine", "Rules-based optimal carrier and service selection"],
  ["Track and Trace Service", "End-to-end cross-carrier shipment visibility"],
  ["Dock Scheduling System", "Inbound and outbound dock appointment and slot management"],
  ["Cross-docking Manager", "Transfer goods between inbound and outbound without storage"],
  ["Distribution Network Optimizer", "Model and optimize warehouse and DC network locations"],
  ["Sourcing Platform", "Supplier discovery, RFQ management, and bid evaluation"],

  // Analytics & Data (28)
  ["Data Warehouse", "Historical enterprise data storage, modeling, and query"],
  ["Business Intelligence Tool", "Self-service BI, drag-and-drop report builder, and dashboards"],
  ["Real-Time Analytics Engine", "Sub-second streaming data aggregation and analytics"],
  ["Data Lake Platform", "Raw data storage, cataloging, and ad-hoc exploration"],
  ["ETL Pipeline Service", "Data extraction, transformation, loading, and scheduling"],
  ["Data Quality Manager", "Data quality rules, profiling, monitoring, and remediation"],
  ["Master Data Management System", "Authoritative master data for customers, products, and suppliers"],
  ["Metadata Catalog", "Enterprise data discovery, lineage, and governance catalog"],
  ["Data Lineage Tracker", "End-to-end tracking of data flows and transformations"],
  ["Event Streaming Platform", "High-throughput event streaming infrastructure"],
  ["Time-Series Database", "High-frequency metrics and sensor data ingest and query"],
  ["Graph Database Service", "Relationship and network data modeling and traversal"],
  ["Feature Store", "Shared ML feature computation, storage, and serving"],
  ["ML Model Registry", "Model versioning, artifact storage, deployment, and monitoring"],
  ["Experiment Tracking Platform", "A/B test and ML experiment lifecycle management"],
  ["Data Science Workbench", "Collaborative notebook and compute environment"],
  ["AutoML Service", "Automated model training, evaluation, and hyperparameter tuning"],
  ["Data Virtualization Layer", "Virtual query federation across heterogeneous data sources"],
  ["Semantic Layer Service", "Business metric definitions, governance, and consistent calculation"],
  ["OLAP Engine", "Multi-dimensional analytical cube processing and query"],
  ["Data Marketplace", "Internal data product discovery, subscription, and sharing"],
  ["Usage Analytics Service", "Platform and feature usage event tracking"],
  ["Product Analytics Platform", "Product engagement, funnel, and retention analytics"],
  ["Web Analytics Service", "Website traffic, session, and conversion analysis"],
  ["App Analytics SDK", "Mobile app performance, crash, and usage event tracking"],
  ["Behavioral Analytics Engine", "User behavior sequence modeling and cohort analysis"],
  ["Customer Attribution Platform", "Multi-touch marketing attribution modeling"],
  ["Conversion Analytics Service", "Funnel conversion analysis and drop-off identification"],

  // Infrastructure & Platform (28)
  ["Service Mesh", "Inter-service communication, traffic management, and mTLS"],
  ["Load Balancer", "Traffic distribution, health checking, and failover routing"],
  ["DNS Service", "Domain name resolution, routing policies, and zone management"],
  ["CDN Platform", "Global content caching, edge delivery, and origin offload"],
  ["Container Registry", "Docker image storage, scanning, and access control"],
  ["Kubernetes Orchestrator", "Container workload scheduling, scaling, and self-healing"],
  ["Secrets Manager", "Secure secrets, credentials, and key storage with rotation"],
  ["Certificate Manager", "TLS certificate provisioning, renewal, and distribution"],
  ["Log Aggregation Service", "Centralized log collection, parsing, indexing, and search"],
  ["Metrics Collector", "Time-series metrics ingestion, storage, and query"],
  ["Distributed Tracer", "Distributed request tracing and latency profiling"],
  ["Alert Manager", "Alert routing, grouping, deduplication, and on-call escalation"],
  ["Incident Response Platform", "On-call scheduling, incident management, and postmortem workflows"],
  ["Configuration Manager", "Application configuration versioning and dynamic refresh"],
  ["Feature Flag Service", "Progressive feature rollout and runtime configuration"],
  ["Service Discovery", "Dynamic service registration, health checking, and lookup"],
  ["Circuit Breaker Service", "Fault tolerance patterns and cascading failure prevention"],
  ["Rate Limiter", "API rate limiting, throttle policies, and quota enforcement"],
  ["Token Service", "JWT and OAuth 2.0 token issuance, validation, and revocation"],
  ["Permission Manager", "Fine-grained permission definitions and access control evaluation"],
  ["Policy Engine", "Policy-as-code authoring, evaluation, and enforcement"],
  ["Service Catalog", "Self-service infrastructure templates and golden-path provisioning"],
  ["Developer Portal", "API documentation, key management, and developer onboarding"],
  ["Internal Developer Platform", "Streamlined developer workflows, environments, and tooling"],
  ["Platform Engineering Hub", "Platform capabilities, abstractions, and golden-path templates"],
  ["Cloud Cost Optimizer", "Cloud spend visibility, anomaly detection, and rightsizing"],
  ["Infrastructure as Code Platform", "Declarative infrastructure management and drift detection"],
  ["Change Management System", "IT change approval, scheduling, and release coordination"],

  // HR & People (27)
  ["HRIS Core", "Core HR system of record for employee data and org structure"],
  ["Talent Acquisition Platform", "End-to-end recruiting, sourcing, and hiring management"],
  ["Applicant Tracking System", "Candidate pipeline, application tracking, and interview scheduling"],
  ["Employee Onboarding System", "New hire task management, equipment, and access provisioning"],
  ["Performance Management Tool", "Goal setting, performance reviews, and continuous feedback"],
  ["Learning Management System", "Employee training content delivery and completion tracking"],
  ["Compensation Manager", "Salary bands, pay review cycles, and merit planning"],
  ["Benefits Administration Platform", "Health, retirement, and voluntary benefit enrollment"],
  ["Payroll Processing Service", "Accurate multi-jurisdiction payroll calculation and submission"],
  ["Time and Attendance System", "Clock-in, work scheduling, and absence tracking"],
  ["Workforce Scheduling Tool", "Shift planning, coverage management, and swap coordination"],
  ["Succession Planning Platform", "Identify, develop, and track next-generation leaders"],
  ["Employee Survey Tool", "Pulse surveys, engagement measurement, and trend analysis"],
  ["Engagement Analytics Platform", "Workforce engagement drivers and attrition risk modeling"],
  ["HR Analytics Dashboard", "People metrics, workforce composition, and headcount reporting"],
  ["Org Chart Service", "Visual organization structure browsing and management"],
  ["Employee Directory", "Searchable employee profile and contact directory"],
  ["HR Document Manager", "Employee document storage, versioning, and e-signature routing"],
  ["Policy Acknowledgment System", "Policy distribution, read confirmation, and sign-off tracking"],
  ["Leave Management System", "Leave requests, manager approvals, and balance tracking"],
  ["Exit Management Platform", "Offboarding task coordination and knowledge transfer"],
  ["Recognition and Rewards Platform", "Peer recognition, nomination workflows, and reward redemption"],
  ["Employee Wellness Platform", "Health programs, mental well-being resources, and EAP"],
  ["Employee Helpdesk", "HR question answering, case creation, and resolution tracking"],
  ["People Analytics Engine", "Predictive workforce insights and attrition risk scoring"],
  ["Compliance Training Hub", "Mandatory training assignment, completion tracking, and reporting"],
  ["Career Development Platform", "Career paths, skill gap assessment, and development planning"],

  // Marketing & Sales (28)
  ["Marketing Automation Platform", "Automated multi-channel marketing workflow execution"],
  ["Email Campaign Manager", "Email campaign design, scheduling, deliverability, and reporting"],
  ["Social Media Manager", "Social content scheduling, publishing, and engagement tracking"],
  ["SEO Analytics Tool", "Keyword ranking tracking, site audit, and SEO opportunity insights"],
  ["Paid Ads Manager", "PPC and programmatic advertising campaign management"],
  ["Campaign Analytics Platform", "Cross-channel campaign performance consolidation and reporting"],
  ["Lead Scoring Engine", "Behavioral and demographic lead quality scoring"],
  ["Account-Based Marketing Hub", "Targeted programs and orchestration for strategic accounts"],
  ["Partner Portal", "Partner resource access, deal registration, and co-marketing management"],
  ["Affiliate Management Platform", "Affiliate program tracking, attribution, and payout management"],
  ["Referral Program Manager", "Customer referral tracking, reward issuance, and analytics"],
  ["Influencer Management Tool", "Influencer discovery, outreach, and campaign performance tracking"],
  ["Event Management Platform", "Physical and virtual event planning, registration, and logistics"],
  ["Webinar Platform", "Virtual event hosting, registration, and attendee engagement"],
  ["Landing Page Builder", "Conversion-optimized landing page creation and A/B testing"],
  ["Form Builder Service", "Lead capture and data collection form creation and embedding"],
  ["Marketing Attribution Model", "Revenue attribution modeling across marketing touchpoints"],
  ["Sales Enablement Platform", "Sales content management, delivery, and effectiveness tracking"],
  ["Sales Analytics Dashboard", "Pipeline visibility, deal health, and rep performance metrics"],
  ["Territory Planner", "Geographic and account-based territory design and assignment"],
  ["Quota Management System", "Sales quota setting, approval, and attainment tracking"],
  ["Sales Forecasting Engine", "AI-driven revenue forecast generation and scenario modeling"],
  ["Commission Calculator", "Variable incentive compensation calculation and payout processing"],
  ["Contract Management System", "Contract authoring, redline, approval, and storage"],
  ["Configure-Price-Quote System", "Guided selling, product configuration, and quote generation"],
  ["Deal Desk Tool", "Complex deal structuring, exception approvals, and pricing governance"],
  ["Competitive Intelligence Platform", "Market and competitor monitoring and battlecard management"],
  ["Partner Relationship Manager", "Channel partner lifecycle, enablement, and performance management"],

  // Security & Risk (28)
  ["Identity Provider", "Enterprise SAML and OIDC identity and authentication provider"],
  ["Single Sign-On Service", "Federated SSO with seamless application access"],
  ["Multi-Factor Authentication Service", "Step-up and adaptive MFA policy enforcement"],
  ["Privileged Access Manager", "Privileged account vaulting and session recording"],
  ["SIEM Platform", "Security event correlation, threat detection, and alerting"],
  ["Threat Intelligence Service", "Cyber threat feeds, IOC management, and enrichment"],
  ["Vulnerability Scanner", "Automated network, system, and application vulnerability scanning"],
  ["Security Operations Platform", "SOC case management, playbooks, and analyst workflows"],
  ["Data Loss Prevention System", "Sensitive data discovery, classification, and egress blocking"],
  ["Endpoint Protection Platform", "Antivirus, EDR, and device control for endpoints"],
  ["Network Security Monitor", "Network traffic analysis, IDS, and anomaly detection"],
  ["Web Application Firewall", "HTTP attack filtering, bot management, and rate limiting"],
  ["API Security Gateway", "API threat protection, authentication enforcement, and schema validation"],
  ["Zero Trust Network Access", "Identity-aware, context-driven network access control"],
  ["Compliance Scanner", "Automated compliance posture assessment against frameworks"],
  ["GRC Platform", "Governance, risk, and compliance documentation and workflow management"],
  ["Risk Assessment Tool", "Enterprise risk identification, scoring, and treatment planning"],
  ["Third-Party Risk Manager", "Vendor security assessment, questionnaire, and continuous monitoring"],
  ["Business Continuity Platform", "BCP documentation, testing exercises, and recovery management"],
  ["Disaster Recovery Orchestrator", "Automated DR failover orchestration and runbook execution"],
  ["Backup Manager", "Data backup scheduling, retention policy, and restoration testing"],
  ["Security Incident Handler", "Security incident response playbook automation and coordination"],
  ["Digital Forensics Analyzer", "Digital artifact collection, preservation, and forensic investigation"],
  ["Security Training Platform", "Security awareness curriculum creation and delivery"],
  ["Phishing Simulator", "Employee phishing awareness testing and reporting"],
  ["Bug Bounty Platform", "Vulnerability disclosure program management and triage"],
  ["Code Security Scanner", "SAST and SCA scanning integrated into CI pipelines"],
  ["Container Security Scanner", "Container image vulnerability scanning and runtime protection"],

  // Integration & Operations (29)
  ["Enterprise Service Bus", "Centralized message routing, transformation, and protocol mediation"],
  ["Integration Platform", "iPaaS for connecting SaaS, on-premise, and cloud systems"],
  ["EDI Gateway", "B2B electronic data interchange translation and exchange"],
  ["B2B Integration Hub", "Trading partner onboarding, mapping, and message management"],
  ["Webhook Manager", "Outbound webhook delivery, retry logic, and monitoring"],
  ["GraphQL Federation Gateway", "Unified GraphQL supergraph across distributed subgraphs"],
  ["gRPC Proxy Service", "Protocol translation, load balancing, and gRPC traffic management"],
  ["Event Bridge", "Cross-account and cross-service event routing and filtering"],
  ["Data Sync Service", "Bidirectional real-time data synchronization between systems"],
  ["Middleware Manager", "Legacy middleware configuration, monitoring, and administration"],
  ["Legacy Integration Adapter", "Adapters and connectors for mainframe and legacy systems"],
  ["Data Migration Tool", "Bulk data migration, validation, and reconciliation between systems"],
  ["Document Management System", "Document storage, versioning, retrieval, and access control"],
  ["Digital Signature Platform", "Legally binding e-signatures, audit trails, and certificate management"],
  ["Collaboration Platform", "Internal team messaging, channels, and file sharing"],
  ["Video Conferencing Service", "Virtual meeting hosting, recording, and screen sharing"],
  ["Project Management Tool", "Project planning, task tracking, milestones, and resource allocation"],
  ["Wiki Platform", "Internal knowledge documentation, search, and versioning"],
  ["IT Service Management System", "ITIL-based service desk, change, and incident management"],
  ["IT Asset Management System", "Hardware and software asset lifecycle and license tracking"],
  ["IT Operations Platform", "NOC tooling, runbooks, and operations management workflows"],
  ["Low-Code Development Platform", "Visual application builder for citizen developers"],
  ["Workflow Automation Engine", "Business process automation with no-code rule configuration"],
  ["Robotic Process Automation", "Bot-driven repetitive task automation for legacy systems"],
  ["Print Management System", "Centralized print queue, policy, and cost allocation management"],
  ["Label Generation Service", "Barcode, QR code, and shipping label generation"],
  ["IoT Platform", "Device connectivity, data ingestion, and fleet management"],
  ["Digital Twin Service", "Virtual replicas of physical assets, processes, and environments"],
  ["Blockchain Integration Service", "Distributed ledger integration for provenance and traceability"],
];

export const COMPONENTS: ComponentDef[] = RAW.map(([name, description]) => ({ name, description }));
