// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.easi.io/support",
            "email": "support@easi.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/components": {
            "get": {
                "description": "Retrieves all application components with cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Get all application components",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination (opaque token)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new application component in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Create a new application component",
                "parameters": [
                    {
                        "description": "Component data",
                        "name": "component",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.CreateApplicationComponentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/components/{id}": {
            "get": {
                "description": "Retrieves a specific application component by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Get an application component by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations": {
            "get": {
                "description": "Retrieves all component relations with cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get all component relations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination (opaque token)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new relation between two application components",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Create a new component relation",
                "parameters": [
                    {
                        "description": "Relation data",
                        "name": "relation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.CreateComponentRelationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/from/{componentId}": {
            "get": {
                "description": "Retrieves all relations where the specified component is the source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get relations from a component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/to/{componentId}": {
            "get": {
                "description": "Retrieves all relations where the specified component is the target",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get relations to a component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/{id}": {
            "get": {
                "description": "Retrieves a specific component relation by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get a component relation by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views": {
            "get": {
                "description": "Retrieves all architecture views",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Get all architecture views",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new architecture view for organizing components",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Create a new architecture view",
                "parameters": [
                    {
                        "description": "View data",
                        "name": "view",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.CreateViewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}": {
            "get": {
                "description": "Retrieves a specific architecture view by its ID with all component positions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Get an architecture view by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/components": {
            "post": {
                "description": "Adds a component to an architecture view at a specific position",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Add a component to a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Component data",
                        "name": "component",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.AddComponentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/components/{componentId}/position": {
            "patch": {
                "description": "Updates the position of a component in an architecture view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Update component position in a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Position data",
                        "name": "position",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.UpdatePositionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "relationType": {
                    "type": "string"
                },
                "sourceComponentId": {
                    "type": "string"
                },
                "targetComponentId": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ComponentPositionDTO"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architectureviews_application_readmodels.ComponentPositionDTO": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "easi_backend_internal_shared_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_shared_api.PaginatedResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/easi_backend_internal_shared_api.PaginationInfo"
                }
            }
        },
        "easi_backend_internal_shared_api.PaginationInfo": {
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "Next cursor if hasMore is true",
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "easi_backend_internal_shared_api.SuccessResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {}
            }
        },
        "internal_architecturemodeling_infrastructure_api.CreateApplicationComponentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.CreateComponentRelationRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "relationType": {
                    "type": "string"
                },
                "sourceComponentId": {
                    "type": "string"
                },
                "targetComponentId": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.PaginatedResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/easi_backend_internal_shared_api.PaginationInfo"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.AddComponentRequest": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.CreateViewRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.UpdatePositionRequest": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EASI Architecture Modeling API",
	Description:      "API for Enterprise Architecture System Integration - Component Modeling",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
