// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.easi.io/support",
            "email": "support@easi.io"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/capabilities": {
            "get": {
                "description": "Retrieves all business capabilities in the capability map",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get all business capabilities",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new business capability in the capability map",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Create a new business capability",
                "parameters": [
                    {
                        "description": "Capability data",
                        "name": "capability",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.CreateCapabilityRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.CapabilityDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/metadata": {
            "get": {
                "description": "Returns HATEOAS links to all capability metadata endpoints",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "List available metadata types",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.MetadataIndexDTO"
                        }
                    }
                }
            }
        },
        "/capabilities/metadata/maturity-levels": {
            "get": {
                "description": "Returns the list of valid maturity level options for capabilities based on Wardley mapping evolution stages (Genesis, Custom Build, Product, Commodity)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get valid maturity levels",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.MaturityLevelDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/capabilities/metadata/ownership-models": {
            "get": {
                "description": "Returns ownership classification options (TribeOwned, TeamOwned, Shared, EnterpriseService)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get valid ownership models",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.OwnershipModelDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/capabilities/metadata/statuses": {
            "get": {
                "description": "Returns lifecycle statuses for capabilities (Active, Planned, Deprecated)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get valid capability statuses",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.StatusDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/capabilities/metadata/strategy-pillars": {
            "get": {
                "description": "Returns strategic alignment categories (AlwaysOn, Grow, Transform)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get valid strategy pillars",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "array",
                                            "items": {
                                                "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.StrategyPillarDTO"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/capabilities/{id}": {
            "get": {
                "description": "Retrieves a specific business capability by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get a capability by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.CapabilityDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates the name and description of a business capability",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Update a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated capability data",
                        "name": "capability",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.UpdateCapabilityRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.CapabilityDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes a business capability. Cannot delete capabilities that have children.",
                "tags": [
                    "capabilities"
                ],
                "summary": "Delete a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/children": {
            "get": {
                "description": "Retrieves all child capabilities of a specific capability",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get child capabilities",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/dependencies/incoming": {
            "get": {
                "description": "Retrieves all dependencies where the specified capability is the target",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get incoming dependencies for a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/dependencies/outgoing": {
            "get": {
                "description": "Retrieves all dependencies where the specified capability is the source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get outgoing dependencies for a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/experts": {
            "post": {
                "description": "Associates a subject matter expert with a capability",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Add an expert to a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Expert data",
                        "name": "expert",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.AddCapabilityExpertRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/metadata": {
            "put": {
                "description": "Updates metadata fields like maturity level, ownership, and strategy alignment",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Update capability metadata",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Metadata",
                        "name": "metadata",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.UpdateCapabilityMetadataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.CapabilityDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/parent": {
            "patch": {
                "description": "Changes the parent of a capability and recalculates levels for the entire subtree",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Change capability parent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New parent data",
                        "name": "parent",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.ChangeCapabilityParentRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/systems": {
            "get": {
                "description": "Retrieves all application components that realize a specific capability",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Get systems linked to a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Associates an application component with a capability to indicate realization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Link a system to a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "System link data",
                        "name": "system",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.LinkSystemRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.RealizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capabilities/{id}/tags": {
            "post": {
                "description": "Associates a tag with a capability for categorization",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capabilities"
                ],
                "summary": "Add a tag to a capability",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Capability ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Tag data",
                        "name": "tag",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.AddCapabilityTagRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capability-dependencies": {
            "get": {
                "description": "Retrieves all capability dependencies in the system",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability-dependencies"
                ],
                "summary": "Get all capability dependencies",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a dependency relationship between two capabilities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability-dependencies"
                ],
                "summary": "Create a capability dependency",
                "parameters": [
                    {
                        "description": "Dependency data",
                        "name": "dependency",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.CreateDependencyRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.DependencyDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capability-dependencies/{id}": {
            "delete": {
                "description": "Deletes a capability dependency relationship",
                "tags": [
                    "capability-dependencies"
                ],
                "summary": "Delete a capability dependency",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Dependency ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capability-realizations/by-component/{componentId}": {
            "get": {
                "description": "Retrieves all capabilities that are realized by a specific application component",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability-realizations"
                ],
                "summary": "Get capabilities realized by a component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/capability-realizations/{id}": {
            "put": {
                "description": "Updates the realization level and notes for a system-capability link",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "capability-realizations"
                ],
                "summary": "Update a system realization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Realization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated realization data",
                        "name": "realization",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_capabilitymapping_infrastructure_api.UpdateRealizationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.RealizationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes the link between a system and a capability",
                "tags": [
                    "capability-realizations"
                ],
                "summary": "Delete a system realization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Realization ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/components": {
            "get": {
                "description": "Retrieves all application components with cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Get all application components",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination (opaque token)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new application component in the system",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Create a new application component",
                "parameters": [
                    {
                        "description": "Component data",
                        "name": "component",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.CreateApplicationComponentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/components/{id}": {
            "get": {
                "description": "Retrieves a specific application component by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Get an application component by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing application component's name and description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "components"
                ],
                "summary": "Update an application component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated component data",
                        "name": "component",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.UpdateApplicationComponentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations": {
            "get": {
                "description": "Retrieves all component relations with cursor-based pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get all component relations",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of items per page (max 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Cursor for pagination (opaque token)",
                        "name": "after",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.PaginatedResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new relation between two application components",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Create a new component relation",
                "parameters": [
                    {
                        "description": "Relation data",
                        "name": "relation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.CreateComponentRelationRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/from/{componentId}": {
            "get": {
                "description": "Retrieves all relations where the specified component is the source",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get relations from a component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/to/{componentId}": {
            "get": {
                "description": "Retrieves all relations where the specified component is the target",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get relations to a component",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/relations/{id}": {
            "get": {
                "description": "Retrieves a specific component relation by its ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Get a component relation by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing component relation's name and description",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "relations"
                ],
                "summary": "Update a component relation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Relation ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated relation data",
                        "name": "relation",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architecturemodeling_infrastructure_api.UpdateComponentRelationRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views": {
            "get": {
                "description": "Retrieves all architecture views",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Get all architecture views",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new architecture view for organizing components",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Create a new architecture view",
                "parameters": [
                    {
                        "description": "View data",
                        "name": "view",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.CreateViewRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}": {
            "get": {
                "description": "Retrieves a specific architecture view by its ID with all component positions",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Get an architecture view by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Deletes an architecture view (cannot delete default view)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Delete an architecture view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Cannot delete default view",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/components": {
            "post": {
                "description": "Adds a component to an architecture view at a specific position",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Add a component to a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Component data",
                        "name": "component",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.AddComponentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Component already in view",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/components/{componentId}": {
            "delete": {
                "description": "Removes a component from an architecture view without deleting the component",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Remove a component from a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "View or component not found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/components/{componentId}/position": {
            "patch": {
                "description": "Updates the position of a component in an architecture view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Update component position in a view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Component ID",
                        "name": "componentId",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Position data",
                        "name": "position",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.UpdatePositionRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "View or component not found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/default": {
            "put": {
                "description": "Sets an architecture view as the default view",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Set a view as the default view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/views/{id}/name": {
            "patch": {
                "description": "Renames an architecture view",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "views"
                ],
                "summary": "Rename an architecture view",
                "parameters": [
                    {
                        "type": "string",
                        "description": "View ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New view name",
                        "name": "view",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internal_architectureviews_infrastructure_api.RenameViewRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/easi_backend_internal_shared_api.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "easi_backend_internal_architecturemodeling_application_readmodels.ApplicationComponentDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architecturemodeling_application_readmodels.ComponentRelationDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "relationType": {
                    "type": "string"
                },
                "sourceComponentId": {
                    "type": "string"
                },
                "targetComponentId": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architectureviews_application_readmodels.ArchitectureViewDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "components": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/easi_backend_internal_architectureviews_application_readmodels.ComponentPositionDTO"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "edgeType": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "isDefault": {
                    "type": "boolean"
                },
                "layoutDirection": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_architectureviews_application_readmodels.ComponentPositionDTO": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "easi_backend_internal_capabilitymapping_application_readmodels.CapabilityDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "eaOwner": {
                    "type": "string"
                },
                "experts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/easi_backend_internal_capabilitymapping_application_readmodels.ExpertDTO"
                    }
                },
                "id": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "maturityLevel": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "ownershipModel": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                },
                "pillarWeight": {
                    "type": "integer"
                },
                "primaryOwner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strategyPillar": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "easi_backend_internal_capabilitymapping_application_readmodels.DependencyDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "dependencyType": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sourceCapabilityId": {
                    "type": "string"
                },
                "targetCapabilityId": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_capabilitymapping_application_readmodels.ExpertDTO": {
            "type": "object",
            "properties": {
                "addedAt": {
                    "type": "string"
                },
                "contact": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_capabilitymapping_application_readmodels.RealizationDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "capabilityId": {
                    "type": "string"
                },
                "componentId": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "linkedAt": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "realizationLevel": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_shared_api.CollectionMeta": {
            "type": "object",
            "properties": {
                "total": {
                    "description": "Total count if available",
                    "type": "integer"
                }
            }
        },
        "easi_backend_internal_shared_api.CollectionResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {},
                "meta": {
                    "$ref": "#/definitions/easi_backend_internal_shared_api.CollectionMeta"
                }
            }
        },
        "easi_backend_internal_shared_api.ErrorResponse": {
            "type": "object",
            "properties": {
                "details": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "easi_backend_internal_shared_api.PaginatedResponse": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "data": {},
                "pagination": {
                    "$ref": "#/definitions/easi_backend_internal_shared_api.PaginationInfo"
                }
            }
        },
        "easi_backend_internal_shared_api.PaginationInfo": {
            "type": "object",
            "properties": {
                "cursor": {
                    "description": "Next cursor if hasMore is true",
                    "type": "string"
                },
                "hasMore": {
                    "type": "boolean"
                },
                "limit": {
                    "type": "integer"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.CreateApplicationComponentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.CreateComponentRelationRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "relationType": {
                    "type": "string"
                },
                "sourceComponentId": {
                    "type": "string"
                },
                "targetComponentId": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.UpdateApplicationComponentRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architecturemodeling_infrastructure_api.UpdateComponentRelationRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.AddComponentRequest": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.CreateViewRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.RenameViewRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_architectureviews_infrastructure_api.UpdatePositionRequest": {
            "type": "object",
            "properties": {
                "x": {
                    "type": "number"
                },
                "y": {
                    "type": "number"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.AddCapabilityExpertRequest": {
            "type": "object",
            "properties": {
                "contactInfo": {
                    "type": "string"
                },
                "expertName": {
                    "type": "string"
                },
                "expertRole": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.AddCapabilityTagRequest": {
            "type": "object",
            "properties": {
                "tag": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.ChangeCapabilityParentRequest": {
            "type": "object",
            "properties": {
                "parentId": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.CreateCapabilityRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "level": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "parentId": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.CreateDependencyRequest": {
            "type": "object",
            "properties": {
                "dependencyType": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "sourceCapabilityId": {
                    "type": "string"
                },
                "targetCapabilityId": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.LinkSystemRequest": {
            "type": "object",
            "properties": {
                "componentId": {
                    "type": "string"
                },
                "notes": {
                    "type": "string"
                },
                "realizationLevel": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.MaturityLevelDTO": {
            "type": "object",
            "properties": {
                "numericValue": {
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "type": "string",
                    "example": "Genesis"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.MetadataIndexDTO": {
            "type": "object",
            "properties": {
                "_links": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.OwnershipModelDTO": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Tribe Owned"
                },
                "value": {
                    "type": "string",
                    "example": "TribeOwned"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.StatusDTO": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Active"
                },
                "sortOrder": {
                    "type": "integer",
                    "example": 1
                },
                "value": {
                    "type": "string",
                    "example": "Active"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.StrategyPillarDTO": {
            "type": "object",
            "properties": {
                "displayName": {
                    "type": "string",
                    "example": "Always On"
                },
                "value": {
                    "type": "string",
                    "example": "AlwaysOn"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.UpdateCapabilityMetadataRequest": {
            "type": "object",
            "properties": {
                "eaOwner": {
                    "type": "string"
                },
                "maturityLevel": {
                    "type": "string"
                },
                "ownershipModel": {
                    "type": "string"
                },
                "pillarWeight": {
                    "type": "integer"
                },
                "primaryOwner": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "strategyPillar": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.UpdateCapabilityRequest": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "internal_capabilitymapping_infrastructure_api.UpdateRealizationRequest": {
            "type": "object",
            "properties": {
                "notes": {
                    "type": "string"
                },
                "realizationLevel": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "EASI Architecture Modeling API",
	Description:      "API for Enterprise Architecture System Integration - Component Modeling",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
